export const countryCodes = [
  { code: "+1", flag: "🇺🇸", name: "United States" },
  { code: "+44", flag: "🇬🇧", name: "United Kingdom" },
  { code: "+90", flag: "🇹🇷", name: "Turkey" },
  { code: "+49", flag: "🇩🇪", name: "Germany" },
  { code: "+7", flag: "🇷🇺", name: "Russia" },
  { code: "+33", flag: "🇫🇷", name: "France" },
  { code: "+34", flag: "🇪🇸", name: "Spain" },
  { code: "+39", flag: "🇮🇹", name: "Italy" },
  { code: "+86", flag: "🇨🇳", name: "China" },
  { code: "+91", flag: "🇮🇳", name: "India" },
  { code: "+61", flag: "🇦🇺", name: "Australia" },
  { code: "+81", flag: "🇯🇵", name: "Japan" },
  { code: "+55", flag: "🇧🇷", name: "Brazil" },
  { code: "+20", flag: "🇪🇬", name: "Egypt" },
  { code: "+971", flag: "🇦🇪", name: "United Arab Emirates" },
  { code: "+972", flag: "🇮🇱", name: "Israel" },
  { code: "+357", flag: "🇨🇾", name: "Cyprus" },
  // Add more country codes as needed
]
